### ISSUE TITLE
Fix the integration tests setup 

### ISSUE THREAD

**Issue by robert-zaremba** [near-ndc/voting-v1#14]
## Context

Traditionally, the NEAR core  / examples smart contract put integration tests in a totally separate crate. For example the NFT reference implementation has [integration tests](https://github.com/near-examples/NFT/tree/master/integration-tests) outside of the NFT crate and outside of the main workspace (the `integration-tests` are not linked to the root workspace cargo file). Similarly the [`workspace-rs` example](https://github.com/near/workspaces-rs/tree/main/examples) doesn't put integration tests in a `tests` subdirectory of the contract crate.

This is not what a Rustacean would expect. Rust integration tests, per [documentation](https://doc.rust-lang.org/rust-by-example/testing/integration_testing.html) are placed in `/tests` directory (sibling to the `/src` directory). 

We tried to follow the Rust structure by moving the tests to the `tests` directory with a workspace setup, but unfortunately this doesn't work.

```
cd elections
cargo test

# wait 5min
# you will see error that crate "elections" is not found
error[E0433]: failed to resolve: use of undeclared crate or module elections
 --> elections/tests/iah.rs:7:5
  |
7 | use elections::proposal::{HouseType, TokenMetadata, SECOND, VOTE_COST};
  |     ^^^^^^^^^ use of undeclared crate or module elections
```

Moreover, any change in the file will cause long run of the tests, due to recompilation of the workspace.

## Objectives

1. find out why `/elections/tests` integration tests don't compile (what's wrong with the setup).
2. Fix the setup with keeping integration tests in `/elections/tests` (rather than moving them to a separate workspace directory).
3. Make sure the setup is efficient: edit in the file won't cause long wait of tests to compile.

**Comment by mikroskeem** [comment]
Opening a PR shortly to tackle this issue.

**Comment by kalloc** [comment]
registry.wasm is https://github.com/near-ndc/i-am-human/tree/master/contracts/registry ?

**Comment by kalloc** [comment]
@robert-zaremba shall I fix the tests too, because test logic is not compatible with fresh registry contract
